name: Deploy Monitoring Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'helm/**'

env:
  AWS_REGION: eu-central-1
  CLUSTER_NAME: monitoring-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Add Grafana Helm repo
        run: helm repo add grafana https://grafana.github.io/helm-charts

      - name: Update Helm repos
        run: helm repo update

      - name: Deploy Grafana Stack
        run: |
          helm upgrade --install monitoring grafana/grafana-enterprise-stack \
            -f helm/values.yaml \
            --namespace monitoring \
            --create-namespace