loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
    config:
      auth_enabled: false
      server:
        http_listen_port: 3100
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          shared_store: filesystem
  promtail:
    enabled: true
  grafana:
    enabled: false

mimir:
  persistence:
    enabled: true
    size: 10Gi
  replicas: 1

tempo:
  persistence:
    enabled: true
    size: 10Gi

grafana:
  persistence:
    enabled: true
    size: 10Gi
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
        - name: Mimir
          type: prometheus
          url: http://mimir:9009
          access: proxy
        - name: Tempo
          type: tempo
          url: http://tempo:3200
          access: proxy

grafana-agent:
  enabled: true
  metrics:
    enabled: true

fluent-bit:
  enabled: true