loki:
  enabled: true
  singleBinary:
    enabled: true
    replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  monitoring:
    lokiCanary:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
  test:
    enabled: false

mimir:
  persistence:
    enabled: true
    size: 10Gi
  replicas: 1

tempo:
  persistence:
    enabled: true
    size: 10Gi

grafana:
  persistence:
    enabled: true
    size: 10Gi
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
        - name: Mimir
          type: prometheus
          url: http://mimir:9009
          access: proxy
        - name: Tempo
          type: tempo
          url: http://tempo:3200
          access: proxy

grafana-agent:
  enabled: true
  metrics:
    enabled: true

fluent-bit:
  enabled: true